name: phydms-latest
dependencies:
  - python
  - pip
  - setuptools
  - wheel

  - cython
  - numpy

  # Dependencies installed during pip install phydms
  # - biopython
  # - scipy
  # - matplotlib
  # - natsort
  # - sympy
  # - six
  # - pandas
  # - pyvolve
  # - statsmodels
  # - weblogo
  # - pypdf2

  # Runtime requirement
  - raxml

  # For running R-scripts in tutorial
  - r-base
  - r-ggplot2
